name: Deploy

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release Version'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Login to Yandex Container Registry
      run: echo ${{ secrets.YANDEX_OAUTH_TOKEN }} | docker login --username oauth --password-stdin cr.yandex
    
    - name: SSH and Deploy
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_KEY }}
        script: |
          docker pull cr.yandex/${{ secrets.YANDEX_CONTAINER_REGISTRY_ID }}/app:${{ github.event.inputs.release_version }}_latest
          docker run -d -p 80:3000 cr.yandex/${{ secrets.YANDEX_CONTAINER_REGISTRY_ID }}/app:${{ github.event.inputs.release_version }}_latest
