name: Fix Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release Version'
        required: true

jobs:
  fix:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Lint
      run: npm run lint

    - name: Run tests
      run: npm test

    - name: Build Docker image
      run: docker build -t cr.yandex/<identifier>/app:${{ github.event.inputs.release_version }}_fix${{ github.run_number }} .

    - name: Tag Docker image
      run: |
        docker tag cr.yandex/<identifier>/app:${{ github.event.inputs.release_version }}_fix${{ github.run_number }} cr.yandex/<identifier>/app:${{ github.event.inputs.release_version }}_latest
        docker push cr.yandex/<identifier>/app:${{ github.event.inputs.release_version }}_fix${{ github.run_number }}
        docker push cr.yandex/<identifier>/app:${{ github.event.inputs.release_version }}_latest

    - name: Create fix release issue
      uses: actions-ecosystem/action-create-issue@v1
      with:
        title: Fix Release ${{ github.event.inputs.release_version }}_fix${{ github.run_number }}
        body: |
          Fix Release details:
          - Date: ${{ github.event.created_at }}
          - Author: ${{ github.actor }}
          - Fix Version: ${{ github.run_number }}
          - Docker Image: cr.yandex/<identifier>/app:${{ github.event.inputs.release_version }}_fix${{ github.run_number }}
