name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.2.0'

    - name: Install dependencies
      run: npm ci

    - name: Lint
      run: npm run lint

    - name: Run tests
      run: npm run test

    - name: Login to Yandex Container Registry
      run: echo ${{ secrets.YANDEX_OAUTH_TOKEN }} | docker login --username oauth --password-stdin cr.yandex


    - name: Build Docker image
      run: docker build -t cr.yandex/${{ secrets.YANDEX_CONTAINER_REGISTRY_ID }}/app:${{ github.run_number }} .

    - name: Tag Docker image
      run: |
        docker tag cr.yandex/${{ secrets.YANDEX_CONTAINER_REGISTRY_ID }}/app:${{ github.run_number }} cr.yandex/${{ secrets.YANDEX_CONTAINER_REGISTRY_ID }}/app:${{ github.run_number }}_latest
        docker push cr.yandex/${{ secrets.YANDEX_CONTAINER_REGISTRY_ID }}/app:${{ github.run_number }}
        docker push cr.yandex/${{ secrets.YANDEX_CONTAINER_REGISTRY_ID }}/app:${{ github.run_number }}_latest

    - name: Create release branch
      run: git checkout -b releases/${{ github.run_number }} && git push origin releases/${{ github.run_number }}
    
    - name: Generate Changelog
      run: |
        echo ${{ github.run_number }} > CHANGELOG.md
    
    - name: Commit and Push Changelog
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git checkout -b update-changelog-v${{ github.run_number }}
        git add CHANGELOG.md
        git commit -m "Update changelog for release v${{ github.run_number }}"
        git push origin update-changelog-v${{ github.run_number }}
    
    - name: Create Pull Request for Changelog
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { data: pullRequest } = await github.pulls.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: `Update changelog for release v${{ github.run_number }}`,
            head: `update-changelog-v${{ github.run_number }}`,
            base: 'main',
            body: 'This PR updates the changelog for release v${{ github.run_number }}.',
          });
          console.log(`Created pull request: ${pullRequest.html_url}`);

    - name: Create release issue
      uses: actions/github-script@v5
      with:
        script: |
          const fs = require('fs');
          const releaseDate = new Date().toISOString().split('T')[0];
          const author = '${{ github.actor }}';
          const version = '${{ github.run_number }}';
          const dockerImage = `cr.yandex/${{ secrets.YANDEX_CONTAINER_REGISTRY_ID }}/app:${version}`;
          const changelog = fs.readFileSync('CHANGELOG.md', 'utf8');
          await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: `Release v${version}`,
            body: `
              **Release Date**: ${releaseDate}
              **Author**: ${author}
              **Version**: v${version}
              **Docker Image**: ${dockerImage}

              ## Changelog
              ${changelog}
            `
          });
