name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.2.0'

    - name: Install dependencies
      run: npm ci

    - name: Lint
      run: npm run lint

    - name: Run tests
      run: npm run test

    - name: Build Docker image
      run: docker build -t cr.yandex/<crpohvkorh9buccodhle>/app:${{ github.run_number }} .

    - name: Tag Docker image
      run: |
        docker tag cr.yandex/<crpohvkorh9buccodhle>/app:${{ github.run_number }} cr.yandex/<crpohvkorh9buccodhle>/app:${{ github.run_number }}_latest
        docker push cr.yandex/<crpohvkorh9buccodhle>/app:${{ github.run_number }}
        docker push cr.yandex/<crpohvkorh9buccodhle>/app:${{ github.run_number }}_latest

    - name: Create release branch
      run: git checkout -b releases/${{ github.run_number }} && git push origin releases/${{ github.run_number }}

    - name: Create release issue
      uses: actions-ecosystem/action-create-issue@v1
      with:
        title: Release ${{ github.run_number }}
        body: |
          Release details:
          - Date: ${{ github.event.created_at }}
          - Author: ${{ github.actor }}
          - Version: ${{ github.run_number }}
          - Docker Image: cr.yandex/<crpohvkorh9buccodhle>/app:${{ github.run_number }}
